// webapp/src/routes/home/+page.svelte
<head>
	<meta
		name="description"
		content="Home automation and collaborative family household management"
	/>
	<title>British Empire Management</title>
</head>

<nav class="flex flex-wrap items-center bg-stone-800 p-3">
	<p class="py-1 pr-3 text-2xl tracking-tight text-white">
		British Empire Management : Home
	</p>
</nav>

<script>
	const data = {
    id: 1,
    owner: 'nick.brett1@gmail.com',
    categories: [
      {
        id: 2,
        name: 'Galactic Unicorn',
        items: [
          {
            id: 3,
            name: 'Passport',
            value: '123456789',
          },
          {
            id: 4,
            name: 'BA Executive Club',
            value: '123456789',
          },
          {
            id: 5,
            name: 'Known Traveler Number',
            value: '123456789',
          },
          {
            id: 6,
            name: 'Jet Blue TrueBlue',
            value: '123456789',
          },
        ],
      },
      {
        id: 6,
        name: 'Hyatt Suite Checker',
        items: [
          {
            id: 7,
            name: 'National Insurance Number',
            value: '123456789',
          },
          {
            id: 8,
            name: 'Social Security Number',
            value: '123456789',
          },
        ],
      },
      {
        id: 9,
        name: 'Chase Monthly',
        items: [
          {
            id: 10,
            name: 'Two Sigma Dental Group Number',
            value: '123456789',
          },
        ],
      },
			{
				id: 11,
				name: 'driftdb',
			},
			{ id: 12,
				name: 'headless CMS for product ideas',
				value: 'sanity.io' 
			}
    ],
  };
</script>

<div>
	{#each data.categories as category}
		<div
			key={category.id}
			class="max-w-sm overflow-hidden rounded shadow-lg"
		>
			<div class="px-6 py-4">
				<div class="mb-2 text-xl font-bold text-white">
					{category.name}
				</div>
			</div> 
		</div>
	{/each}
</div>

// webapp/pages/home.jsx
import React from 'react';

import Head from 'next/head';
import { CldImage } from 'next-cloudinary';
import { useQuery } from 'urql';
import { withUrqlClient } from 'next-urql';

const InfoQuery = `
	query {
		info {
			id
			owner
			categories {
				id
				name
				items {
					id
					name
					value
				}
			}
		}
	}
`;

const render = (data) => (
  <div>
    {data.info.categories.map((category) => (
      <div
        key={category.id}
        className="max-w-sm overflow-hidden rounded shadow-lg"
      >
        <div className="px-6 py-4">
          <div className="mb-2 text-xl font-bold text-white">
            {category.name}
          </div>
        </div>
        <CldImage
          width={600}
          height={800}
          layout="responsive"
          src="https://res.cloudinary.com/dnwdr35zg/image/upload/v1675011729/unionjack.webp"
          alt="Test Image"
          priority
        />
      </div>
    ))}
  </div>
);

function Home() {
  const [result] = useQuery({
    query: InfoQuery,
  });

  const { data, fetching, error } = result;
  if (error) throw new Error(error.message);

  return (
    <>
      <Head>
        <meta
          name="description"
          content="Home automation and collaborative family household management"
        />
        <title>British Empire Management</title>
      </Head>
      <nav className="flex flex-wrap items-center bg-stone-800 p-3">
        <p className="py-1 pr-3 text-2xl tracking-tight text-white">
          British Empire Management : Home
        </p>
      </nav>
      {fetching && <div>Loading...</div>}
      {data && render(data)}
    </>
  );
}

export default withUrqlClient(() => ({
  url: '/graphql',
}))(Home);
